// module name: accept_invite
import 'package:dio/dio.dart';

import '../api_client.dart';

class AcceptInviteService {
  final String serverId;

  Dio get _dio => ApiClient.instance(serverId);

  const AcceptInviteService({required this.serverId});

  /// Accepts an invite generated by SendContactService.generateInvite —
  /// [userId] and [passcode] come from the deeplink the current user
  /// received (e.g. https://.../invite/{userId}-{passcode}).
  ///
  /// Returns the inviting user's public key, raw (the response body is a
  /// plain JSON string, not an object) — the current user's client uses
  /// this to establish a secure/encrypted channel with the inviter.
  ///
  /// Auth (Bearer access token) and refresh-on-401 are handled automatically
  /// by ApiClient's interceptors.
  Future<String> acceptInvite({
    required String userId,
    required String passcode,
  }) async {
    final response = await _dio.post(
      '/api/account/accept-an-invite',
      options: Options(
        headers: {
          'accept': 'application/json',
          'Content-Type': 'application/json',
        },
      ),
      data: {
        'user_id': userId,
        'passcode': passcode,
      },
    );

    return response.data as String;
  }
}